spring:
  application:
    name: platform-cloudbox

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    cloudbox.platform: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
